# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89271d3eb8647ea6a5d138712b05eb18cb985742cdf1059181f4145075f3e30b7b0256ad0563f032b7a69bbf0e5e7605e1890caa2d70c0ea7ca20f50659416eb

test:
  secret_key_base: 36b0a9e00c4633821e8c427ea438e7466bc492abfa6288f8310ae8c4437e00801368c99dbd90d4c56ef7e4d0cfd1304be1f1d9120948a0cdd30bb0f7820c44fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
